name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Устанавливаем Java 17
        distribution: 'adoptopenjdk'  # Укажите дистрибутив Java, если требуется (например, 'adoptopenjdk' или 'zulu')

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
